server: 
  port: 8080
  ssl: 
    enabled: false
      
spring:
  main: 
    allow-bean-definition-overriding: true
    banner-mode: console
  mvc: 
    throw-exception-if-no-handler-found: true
                 
springdoc: 
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui.html
  
parallelism: 
  corepoolsize: 8
  maxpoolsize: 16
  queueCapacity: 10000
 
elasticsearch:
  ip: basic.es.northamerica-northeast1.gcp.elastic-cloud.com:9243